// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package keywords_server

type NewKeyword struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type NewTag struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}
